on:
  push:
    branches:
      - main
    tags:
      - "v*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: zip -r ../calibre-plugin-readwise.zip *
        working-directory: src
      - run: zip calibre-plugin-readwise.zip COPYING README.md
      - uses: actions/upload-artifact@v2
        with:
          name: calibre-plugin-readwise
          path: calibre-plugin-readwise.zip
      - uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Readwise Plugin for Calibre ${{ github.ref }}
          draft: false
          prerelease: false
        if: startsWith(github.ref, 'refs/tags/')
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./calibre-plugin-readwise.zip
          asset_name: calibre-plugin-readwise.zip
          asset_content_type: application/zip
        if: startsWith(github.ref, 'refs/tags/')
